-- MySQL Script generated by MySQL Workbench
-- 11/02/15 11:20:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(20) NOT NULL COMMENT '',
  `hashSenha` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '');


-- -----------------------------------------------------
-- Table `Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livro` ;

CREATE TABLE IF NOT EXISTS `Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(20) NOT NULL COMMENT '',
  `genero` VARCHAR(20) NOT NULL COMMENT '',
  `autor` VARCHAR(20) NOT NULL COMMENT '',
  `editora` VARCHAR(10) NOT NULL COMMENT '',
  `publicacao` DATETIME NOT NULL COMMENT '',
  `preco` DECIMAL(5,2) NOT NULL COMMENT '',
  PRIMARY KEY (`idLivro`)  COMMENT '');


-- -----------------------------------------------------
-- Table `Usuario_avalia_Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario_avalia_Livro` ;

CREATE TABLE IF NOT EXISTS `Usuario_avalia_Livro` (
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Livro_idLivro` INT NOT NULL COMMENT '',
  `nota` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Usuario_idUsuario`, `Livro_idLivro`)  COMMENT '');
