-- MySQL Script generated by MySQL Workbench
-- 11/02/15 11:20:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------


CREATE TABLE Usuario (
  idUsuario INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  nome VARCHAR(20) NOT NULL,
  hashSenha VARCHAR(10) NOT NULL);


-- -----------------------------------------------------
-- Table `Livro`
-- -----------------------------------------------------


CREATE TABLE Livro (
  idLivro INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  titulo VARCHAR(20) NOT NULL,
  genero VARCHAR(20) NOT NULL,
  autor VARCHAR(20) NOT NULL,
  editora VARCHAR(10) NOT NULL,
  publicacao DATE NOT NULL,
  preco DECIMAL(5,2) NOT NULL);


-- -----------------------------------------------------
-- Table `Usuario_avalia_Livro`
-- -----------------------------------------------------

CREATE TABLE Usuario_avalia_Livro(
  idUsuario INTEGER NOT NULL,
  FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario) ON DELETE CASCADE,
  idLivro INTEGER NOT NULL,
  FOREIGN KEY (idLivro) REFERENCES Livro (idLivro) ON DELETE CASCADE,
  nota INTEGER NOT NULL);


